<a href="https://colab.research.google.com/github/hestydms/belajar-intermediate-python-11/blob/main/Assignment_Numpy_Hesty_Dewi_Maria_Siagian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

## 1. Create a 4x4 matrix with values ranging from 0 to 3.

In [4]:
a = np.random.randint(0,4,(4,4))
print(a)

[[3 3 2 0]
 [0 3 1 3]
 [1 2 1 3]
 [1 2 1 1]]


## 2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.

In [8]:
b = np.random.randint(0,4,(4,4))
print("array with shape of 4x4")
print(b)

array with shape of 4x4
[[3 2 2 1]
 [2 2 3 1]
 [0 2 1 3]
 [1 0 0 1]]


In [12]:
b1 = np.vsplit(b,2)
print("array with shape of 4x4 and split 2D vertically")
print(b1)

array with shape of 4x4 and split 2D vertically
[array([[3, 2, 2, 1],
       [2, 2, 3, 1]]), array([[0, 2, 1, 3],
       [1, 0, 0, 1]])]


In [13]:
b2 = np.hsplit(b,2)
print("array with shape of 4x4 and split 2D horizontally")
print(b2)

array with shape of 4x4 and split 2D horizontally
[array([[3, 2],
       [2, 2],
       [0, 2],
       [1, 0]]), array([[2, 1],
       [3, 1],
       [1, 3],
       [0, 1]])]
